print("this is the 1st line")
print("this is the 2nd line")
print("this is the 3rd line")
print("Hello from main branch!")
print("login feature branch")
print("Hello from Mousul city")
print("Adding hero section")
print("Adding about-me section")
print("Adding header")
print("adding footer")
print("adding announcement")
print("adding form section")
print("add IT department")
print("changing the picture")
print("adding address information")
print("adding new hero picture")
print("Hello instructor")
print("adding while loop")
print("adding feature from locally")
print("adding news section")
print("updating location")
print("updating hero")
print("adding new-section pictures")
print("adding new-section location")
print("change the font of the new section")
print("adding logo to the new section")
