print("this is the 1st line")
print("this is the 2nd line")
print("this is the 3rd line")
print("Hello from main branch!")
print("login feature branch")
print("Hello from Mousul city")
print("Adding hero section")
print("Adding about-me section")
print("Adding header")
print("adding footer")
print("test update")
print("adding form section")
print("add IT department")
print("changing the picture")
print("adding address information")
print("adding new hero picture")
print("Hello instructor")
print("adding while loop")
print("adding feature from locally")
print("adding news section")