print("this is the 1st line")
print("this is the 2nd line")
print("this is the 3rd line")
print("Adding greeting message!")
print("login feature branch")
print("Adding form section")
print("Adding hero section")
print("Adding about-me section")
print("Adding header")
print("adding footer")